#!/usr/bin/env node
/**
 * MLS Backend Bootstrap Script
 * 
 * Zero-dependency setup — runs with vanilla Node.js.
 * Usage: node setup.js
 * 
 * What it does:
 *   1. Creates .env from .env.example if missing
 *   2. Installs npm dependencies if node_modules is missing
 *   3. Generates Prisma clients for both schemas
 *   4. Pushes database schemas (creates tables)
 *   5. Seeds database if it's empty
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const ENV_FILE = path.join(ROOT, '.env');
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const NODE_MODULES = path.join(ROOT, 'node_modules');
const DEV_DB = path.join(ROOT, 'prisma', 'dev.db');
const INTEL_DB = path.join(ROOT, 'prisma', 'intelligence.db');

// ── Helpers ──────────────────────────────────────────────────

function log(emoji, msg) {
    console.log(`${emoji}  ${msg}`);
}

function run(cmd, label) {
    log('⚙️', label || cmd);
    try {
        execSync(cmd, { cwd: ROOT, stdio: 'inherit' });
        return true;
    } catch (e) {
        console.error(`   ❌ Failed: ${cmd}`);
        console.error(`   ${e.message}`);
        return false;
    }
}

function fileExists(p) {
    return fs.existsSync(p);
}

// ── Step 1: .env ─────────────────────────────────────────────

function ensureEnv() {
    if (fileExists(ENV_FILE)) {
        log('✅', '.env exists');
        return;
    }

    log('📄', 'Creating .env from .env.example...');

    if (fileExists(ENV_EXAMPLE)) {
        let content = fs.readFileSync(ENV_EXAMPLE, 'utf-8');

        // Ensure DATABASE_URL has a value for local dev
        if (content.includes('DATABASE_URL=\n') || content.includes('DATABASE_URL=\r')) {
            content = content.replace(/DATABASE_URL=(\r?\n)/, 'DATABASE_URL=file:./dev.db$1');
        }

        // Set NODE_ENV to development
        content = content.replace(/NODE_ENV=production/, 'NODE_ENV=development');

        fs.writeFileSync(ENV_FILE, content);
        log('✅', '.env created with SQLite defaults');
    } else {
        // Fallback: create minimal .env
        const minimal = [
            '# Auto-generated by setup.js',
            'PORT=3001',
            'NODE_ENV=development',
            'DATABASE_URL=file:./dev.db',
            'NEXT_PUBLIC_API_URL=http://localhost:3001',
            ''
        ].join('\n');
        fs.writeFileSync(ENV_FILE, minimal);
        log('✅', '.env created with minimal defaults');
    }
}

// ── Step 2: Dependencies ─────────────────────────────────────

function ensureDeps() {
    if (fileExists(NODE_MODULES)) {
        log('✅', 'node_modules exists');
        return true;
    }

    log('📦', 'Installing dependencies...');
    return run('npm install', 'Running npm install...');
}

// ── Step 3: Prisma Generate ──────────────────────────────────

function generatePrisma() {
    log('🔧', 'Generating Prisma clients...');
    const ok1 = run('npx prisma generate --schema=prisma/schema.prisma', 'Generating core client...');
    const ok2 = run('npx prisma generate --schema=prisma/schema.intelligence.prisma', 'Generating intelligence client...');
    return ok1 && ok2;
}

// ── Step 4: Push Schemas ─────────────────────────────────────

function pushSchemas() {
    log('🗄️', 'Pushing database schemas...');
    const ok1 = run('npx prisma db push --schema=prisma/schema.prisma --skip-generate', 'Pushing core schema...');
    const ok2 = run('npx prisma db push --schema=prisma/schema.intelligence.prisma --skip-generate', 'Pushing intelligence schema...');
    return ok1 && ok2;
}

// ── Step 5: Seed if empty ────────────────────────────────────

function seedIfEmpty() {
    // Quick check: if dev.db is tiny (< 50KB), it's likely empty
    if (fileExists(DEV_DB)) {
        const stats = fs.statSync(DEV_DB);
        if (stats.size > 50 * 1024) {
            log('✅', `Database has data (${(stats.size / 1024).toFixed(0)}KB)`);
            return true;
        }
    }

    log('🌱', 'Seeding database with mock data...');
    return run('npx tsx scripts/seed-data.ts', 'Running seed script...');
}

// ── Step 6: Validate ─────────────────────────────────────────

function validate() {
    log('🔍', 'Validating setup...');

    const checks = [
        { name: '.env', ok: fileExists(ENV_FILE) },
        { name: 'node_modules', ok: fileExists(NODE_MODULES) },
        { name: 'Core Prisma client', ok: fileExists(path.join(ROOT, 'src', 'generated', 'client-core', 'index.js')) },
        { name: 'Intelligence Prisma client', ok: fileExists(path.join(ROOT, 'src', 'generated', 'client-intelligence', 'index.js')) },
        { name: 'Core database', ok: fileExists(DEV_DB) },
        { name: 'Intelligence database', ok: fileExists(INTEL_DB) },
    ];

    console.log('');
    console.log('┌─────────────────────────────────────────┐');
    console.log('│         MLS Setup Status                 │');
    console.log('├─────────────────────────────────────────┤');

    let allOk = true;
    for (const c of checks) {
        const icon = c.ok ? '✅' : '❌';
        console.log(`│  ${icon}  ${c.name.padEnd(33)}│`);
        if (!c.ok) allOk = false;
    }

    console.log('├─────────────────────────────────────────┤');
    if (allOk) {
        console.log('│  🚀 Ready! Run: npm run dev              │');
    } else {
        console.log('│  ⚠️  Some checks failed — see above      │');
    }
    console.log('└─────────────────────────────────────────┘');
    console.log('');

    return allOk;
}

// ── Main ─────────────────────────────────────────────────────

async function main() {
    console.log('');
    console.log('╔═══════════════════════════════════════╗');
    console.log('║     MLS Backend Bootstrap v1.0        ║');
    console.log('╚═══════════════════════════════════════╝');
    console.log('');

    ensureEnv();

    if (!ensureDeps()) {
        console.error('❌ npm install failed. Fix errors above and try again.');
        process.exit(1);
    }

    if (!generatePrisma()) {
        console.error('❌ Prisma generate failed. Fix errors above and try again.');
        process.exit(1);
    }

    if (!pushSchemas()) {
        console.error('❌ Schema push failed. Fix errors above and try again.');
        process.exit(1);
    }

    seedIfEmpty();

    const ok = validate();
    process.exit(ok ? 0 : 1);
}

main();
